apiVersion: v1
kind: Secret
metadata:
  name: hardtek-secrets
type: Opaque
data:
  application.properties: |
    jwt.secret.key: t9DqS47x+Em9b8eGnI0O7sWH5PS86IwRL4JjZZ7AKHO1IDBTbcy6Sg/MdY5CMhNl
    jwt.time.expiration: 86400000
    spring.datasource.url: jdbc:mysql://uekoylgwrdq2igzq:UBSHnTrnCgHOZIt7abQW@bty7sho5dbjw5zqxm5yn-mysql.services.clever-cloud.com:3306/bty7sho5dbjw5zqxm5yn
    spring.datasource.username: uekoylgwrdq2igzq
    spring.datasource.password: UBSHnTrnCgHOZIt7abQW
    spring.mail.host: smtp.gmail.com
    spring.mail.port: 587
    spring.mail.username: gonzalovalloneivan@gmail.com
    spring.mail.password: inqbewidbfoemwft
    spring.mail.properties.mail.smtp.auth: true
    spring.mail.properties.mail.smtp.starttls.enable: true
    spring.mail.properties.mail.smtp.from: gonzalovalloneivan@gmail.com
